title: David Bindel
email: bindel@cornell.edu
description: CS 4220 home page
baseurl: "/courses/CS4220/2023sp/"
url: "http://www.cs.cornell.edu/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]

markdown: kramdown
